# Generated by Django 5.2 on 2025-05-08 18:51

import doctor_info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_info', '0002_doctorinfo_divisions_doctorinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=doctor_info.models.upload_to),
        ),
    ]
