# Generated by Django 5.2 on 2025-05-08 06:05

import doctor_info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='divisions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=doctor_info.models.upload_to),
        ),
    ]
