# Generated by Django 5.2 on 2025-05-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_info', '0003_alter_doctorinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='photo',
            field=models.ImageField(blank=True, default='doctor_info/images/default.jpg', null=True, upload_to='doctor_info/images/'),
        ),
    ]
